export { default as daniel_gutierrez } from './daniel_gutierrez.jpeg'
export { default as paula_rojas } from './paula_rojas.jpg'
export { default as sofia_garcia } from './sofia_garcia.jpeg'
export { default as alejandro_tayak } from './alejandro_tayak.jpg'
export { default as julian_lozano } from './julian_lozano.jpeg'